substitutions:
  plug_name: pte_v0.1
esphome:
  name: pte
  platform: ESP8266
  board: nodemcuv2

wifi:
  # ssid: "NPM Wi-Fi"
  # password: "test"
  # manual_ip:
  #   static_ip: 10.4.1.62
  #   gateway: 10.4.1.201
  #   subnet: 255.255.255.0
  ssid: "test"
  password: "testestes"
  # manual_ip:
  #   static_ip: 192.168.1.96
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "hyBhldCbM1t3"
captive_portal:
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "RrsbVyrLG4yxB2AD"
  reboot_timeout: 1000min

ota:
  password: "RrsbVyrLG4yxB2AD"
  
web_server:
  css_url: ""
  css_include: "/config/static/webserver-v1.min.css"
  js_url: ""
  js_include: "/config/static/webserver-v1.min.js"

#D0 status led
status_led:
  pin:
    number: GPIO2
    inverted: yes

switch:
  - platform: gpio
    name: ${plug_name}_switch_relay_door1
    pin: D5
    id: relay
  - platform: gpio
    name: ${plug_name}_switch_relay_door1
    pin: D6
    id: relay1
  - platform: template
    name: "Door1"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay
    - delay: 1000ms
    - switch.turn_on: relay1
    - delay: 2000ms
    - switch.turn_off: relay1
    - switch.turn_off: relay
    - delay: 3500ms
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay
  - platform: gpio
    name: ${plug_name}_switch_relay_door2
    pin: D7
    inverted: yes
    id: relay2
  - platform: template
    name: "Door2"
    turn_on_action:
    - switch.turn_on: relay2
    - delay: 500ms
    - switch.turn_off: relay2
  - platform: gpio
    name: ${plug_name}_switch_relay_shalgbaum_open
    pin: D1
    inverted: false
    id: relay3
  - platform: template
    name: "barrierOpen"
    turn_on_action:
      - switch.turn_on: relay3
      - delay: 5s
      - switch.turn_off: relay3
  - platform: gpio    
    name: ${plug_name}_switch_relay_shalgbaum_close
    pin: D2
    inverted: false
    id: relay4
  - platform: template
    name: "barrierClose"
    turn_on_action:
      - switch.turn_on: relay4
      - delay: 5s
      - switch.turn_off: relay4

sensor:
   - platform: uptime
     name: ${plug_name}_uptime
   - platform: wifi_signal
     name: ${plug_name}_wifi_signal
     update_interval: 60s